name: Preprocessing Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  preprocess-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download dataset
      run: |
        wget -O onlinepaymentfraud_dataset.csv "https://drive.google.com/uc?id=1BnJ4EhL5c8aqL3ZnLB_X5W60HrqFR5jF"

    - name: Check dataset
      run: |
        ls -lh onlinepaymentfraud_dataset.csv
        head -n 5 onlinepaymentfraud_dataset.csv

    - name: Run preprocessing
      run: |
        python preprocessing/automate_Rindumas.py

    - name: Commit preprocessing result
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-update preprocessing dataset"
        file_pattern: "preprocessing/onlinepaymentfraud_preprocessing.csv"